# Generated by Django 3.0.6 on 2020-05-22 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('patronymic', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('month_of_birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_birth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_of_death', models.IntegerField(blank=True, null=True)),
                ('month_of_death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f', to='persons.Person')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m', to='persons.Person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s', to='persons.Person')),
            ],
        ),
    ]
