# Generated by Django 3.0.6 on 2020-05-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_form', models.CharField(max_length=300, verbose_name='Мужская форма')),
                ('female_form', models.CharField(max_length=300, verbose_name='Женская форма')),
            ],
            options={
                'verbose_name': 'Фамилия',
                'verbose_name_plural': 'Фамилии',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('month_of_birth', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'неизвестен'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Месяц рождения')),
                ('day_of_birth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День рождения')),
                ('year_of_death', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('month_of_death', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'неизвестен'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Месяц смерти')),
                ('day_of_death', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День смерти')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('birth_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_born', to='persons.Location')),
                ('burial_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_buried', to='persons.Location')),
                ('ex_spouses', models.ManyToManyField(blank=True, related_name='ex_spouses_reverse', to='persons.Person')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_father', to='persons.Person')),
                ('living_locations', models.ManyToManyField(blank=True, related_name='persons_living', to='persons.Location')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_mother', to='persons.Person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_reverse', to='persons.Person')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='persons.Surname')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
    ]
