# Generated by Django 3.0.6 on 2020-05-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_born', to='persons.Location', verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='burial_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_buried', to='persons.Location', verbose_name='Место захоронения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ex_spouses',
            field=models.ManyToManyField(blank=True, related_name='ex_spouses_reverse', to='persons.Person', verbose_name='Бывшие супруги'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_father', to='persons.Person', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='living_locations',
            field=models.ManyToManyField(blank=True, related_name='persons_living', to='persons.Location', verbose_name='Места жительства'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_mother', to='persons.Person', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_reverse', to='persons.Person', verbose_name='Супруг(-а)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='persons.Surname', verbose_name='Фамилия'),
        ),
    ]
