# Generated by Django 3.0.6 on 2020-06-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200524_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ex_spouses',
            field=models.ManyToManyField(blank=True, related_name='_person_ex_spouses_+', to='persons.Person', verbose_name='Бывшие супруги'),
        ),
    ]
