# Generated by Django 3.0.6 on 2020-05-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20200522_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_reverse', to='persons.Person'),
        ),
    ]
