# Generated by Django 3.0.6 on 2020-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20200522_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='living_locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons_living', to='persons.Location'),
        ),
    ]
